site_name: QtForge Documentation
site_description: Modern C++ Plugin System for Qt Applications
site_author: QtForge Team
site_url: https://qtforge.github.io/QtForge/

# Repository
repo_name: AstroAir/QtForge
repo_url: https://github.com/AstroAir/QtForge
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 QtForge Team

# Configuration
theme:
  name: material
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true



# Customization
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AstroAir/QtForge
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/QtForge


# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: AstroAir
      repo: QtForge
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/overview.md
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - First Plugin: getting-started/first-plugin.md
  - User Guide:
    - Plugin Management: user-guide/plugin-management.md
    - Plugin Architecture: user-guide/plugin-architecture.md
    - Python Integration: user-guide/python-integration.md
    - Security Configuration: user-guide/security-configuration.md
    - Configuration: user-guide/configuration.md
    - Advanced Plugin Development: user-guide/advanced-plugin-development.md
    - Marketplace Integration: user-guide/marketplace-integration.md
    - Workflow Orchestration: user-guide/workflow-orchestration.md
    - Troubleshooting: user-guide/troubleshooting.md
  - Guides:
    - readme.md: guides/readme.md
    - Architecture: guides/architecture.md
    - Plugin Development: developer-guide/plugin-development.md
  - API Reference:
    - Overview: api/index.md
    - API Overview: api/overview.md
    - Core:
      - API Reference: api/readme.md
      - Plugin Interface: api/core/plugin-interface.md
      - Plugin Manager: api/core/plugin-manager.md
      - Plugin Loader: api/core/plugin-loader.md
      - Plugin Registry: api/core/plugin-registry.md
    - Communication:
      - Message Bus: api/communication/message-bus.md
      - Message Types: api/communication/message-types.md
    - Security:
      - Security Manager: api/security/security-manager.md
      - Plugin Validator: api/security/plugin-validator.md
      - Permission Manager: api/security/permission-manager.md
      - Threat Detector: api/security/threat-detector.md
    - Utils:
      - Error Handling: api/utils/error-handling.md
      - Serialization: api/utils/serialization.md
    - Composition:
      - Composite Plugin: api/composition/composite-plugin.md
    - Lua:
      - Overview: api/lua/overview.md
    - Marketplace:
      - Plugin Marketplace: api/marketplace/plugin-marketplace.md
    - Monitoring:
      - Plugin Hot Reload Manager: api/monitoring/plugin-hot-reload-manager.md
      - Plugin Metrics Collector: api/monitoring/plugin-metrics-collector.md
      - Resource Monitor: api/monitoring/resource-monitor.md
    - Orchestration:
      - Plugin Orchestrator: api/orchestration/plugin-orchestrator.md
    - Python:
      - Overview: api/python/overview.md
      - Core:
        - Plugin Interface: api/python/core/plugin-interface.md
        - Plugin Loader: api/python/core/plugin-loader.md
        - Plugin Manager: api/python/core/plugin-manager.md
      - Orchestration:
        - Plugin Orchestrator: api/python/orchestration/plugin-orchestrator.md
    - Transactions:
      - Plugin Transaction Manager: api/transactions/plugin-transaction-manager.md
      - Transaction Manager: api/transactions/transaction-manager.md
  - Tutorials:
    - Getting Started Tutorial: tutorials/getting-started-tutorial.md
    - Advanced Plugin Tutorial: tutorials/advanced-plugin-tutorial.md
    - Orchestration Tutorial: tutorials/orchestration-tutorial.md
    - Python Integration Tutorial: tutorials/python-integration-tutorial.md
  - Examples:
    - Overview: examples/index.md
    - Basic Plugin Examples: examples/basic-plugin-examples.md
    - Service Plugin: examples/service-plugin.md
    - Network Plugin: examples/network-plugin.md
    - UI Plugin: examples/ui-plugin.md
    - Advanced Patterns: examples/advanced-patterns.md
    - Advanced Plugin Examples: examples/advanced-plugin-examples.md
    - Python Examples: examples/python-examples.md
    - Orchestration Examples: examples/orchestration-examples.md
    - Marketplace Examples: examples/marketplace-examples.md
    - Composition Examples: examples/composition-examples.md
    - Hot Reload Examples: examples/hot-reload-examples.md
    - Metrics Examples: examples/metrics-examples.md
    - Multilingual Examples: examples/multilingual-examples.md
  - Developer Guide:
    - Plugin Development: developer-guide/plugin-development.md
    - Plugin Distribution: developer-guide/plugin-distribution.md
    - Best Practices: developer-guide/best-practices.md
    - Advanced Patterns: developer-guide/advanced-patterns.md
  - Architecture:
    - System Design: architecture/system-design.md
  - Advanced Topics:
    - Plugin Composition: user-guide/plugin-composition.md
    - Advanced Security: user-guide/advanced-security.md
    - Advanced Orchestration: user-guide/advanced-orchestration.md
    - Transaction Management: user-guide/transaction-management.md
    - Performance Optimization: user-guide/performance-optimization.md
    - Monitoring: user-guide/monitoring.md
    - Threading: user-guide/threading.md
    - Workflow Orchestration: user-guide/workflow-orchestration.md
    - Troubleshooting: user-guide/troubleshooting.md
  - Bindings:
    - Multilingual Bindings Guide: bindings/multilingual-bindings-guide.md
  - Contributing:
    - Overview: contributing/index.md
    - Testing: contributing/testing.md
  - Appendix:
    - FAQ: appendix/faq.md
    - License: appendix/license.md
  - Additional Resources:
    - Documentation Index: documentation-index.md
    - Security: security.md
    - Version Management: version-management.md
    - Migration Guide: migration-v3-2.md
    - Quick Reference: quick-reference-v3-2.md
    - Lua Plugin Bridge: lua-plugin-bridge.md
    - Plugin Loading Optimizations: plugin-loading-optimizations.md
