"""
QtForge Communication Module Type Stubs

Type definitions for the qtforge.communication submodule.
Contains inter-plugin communication and messaging functionality.
"""

from typing import Any, Dict, List, Optional, Union, Callable
from enum import Enum
import datetime

# Enums
class DeliveryMode(Enum):
    Immediate = ...
    Queued = ...
    Broadcast = ...
    Unicast = ...
    Multicast = ...

class MessagePriority(Enum):
    Low = ...
    Normal = ...
    High = ...
    Critical = ...

class ServiceCapability(Enum):
    None_ = ...
    Synchronous = ...
    Asynchronous = ...
    Streaming = ...
    Transactional = ...
    Cacheable = ...
    Idempotent = ...
    ThreadSafe = ...
    Stateful = ...
    Discoverable = ...
    Versioned = ...
    Authenticated = ...
    Encrypted = ...

# Communication Classes
class IMessage:
    """Base message interface."""
    def type(self) -> str: ...
    def sender(self) -> str: ...
    def timestamp(self) -> Any: ...  # timestamp type from C++
    def priority(self) -> MessagePriority: ...
    def to_json(self) -> Dict[str, Any]: ...
    def metadata(self) -> Dict[str, Any]: ...
    def __repr__(self) -> str: ...

class BasicMessage(IMessage):
    """Basic message implementation."""
    def __init__(self, topic: str, sender: str, data: Dict[str, Any] = {}) -> None: ...
    def set_data(self, data: Dict[str, Any]) -> None: ...
    def set_metadata(self, metadata: Dict[str, Any]) -> None: ...
    def set_priority(self, priority: MessagePriority) -> None: ...

class Subscription:
    """Message subscription information."""
    subscriber_id: str
    message_type: str
    handler: Any
    filter: Any
    is_active: bool
    created_at: Any
    message_count: int
    def __repr__(self) -> str: ...

class IMessageBus:
    """Message bus interface."""
    def unsubscribe(self, subscriber_id: str, message_type: Optional[Any] = None) -> None: ...
    def subscribers(self, message_type: Any) -> List[str]: ...
    def subscriptions(self, subscriber_id: str) -> List[Subscription]: ...
    def has_subscriber(self, subscriber_id: str) -> bool: ...
    def statistics(self) -> Dict[str, Any]: ...
    def clear(self) -> None: ...
    def set_logging_enabled(self, enabled: bool) -> None: ...
    def is_logging_enabled(self) -> bool: ...
    def message_log(self, limit: int = 100) -> List[Dict[str, Any]]: ...

class MessageBus(IMessageBus):
    """Message bus implementation."""
    def __init__(self, parent: Optional[Any] = None) -> None: ...
    def __repr__(self) -> str: ...

# Service Contract Classes
class ServiceVersion:
    """Service version information."""
    major: int
    minor: int
    patch: int
    def __init__(self, major: int = 0, minor: int = 0, patch: int = 0) -> None: ...
    def to_string(self) -> str: ...
    def is_compatible_with(self, other: 'ServiceVersion') -> bool: ...

class ServiceMethodDescriptor:
    """Service method descriptor."""
    def __init__(self) -> None: ...
    method_name: str
    description: str
    input_schema: Dict[str, Any]
    output_schema: Dict[str, Any]
    capabilities: int  # ServiceCapability bitfield
    timeout_ms: int
    def to_json(self) -> Dict[str, Any]: ...
    @staticmethod
    def from_json(json_obj: Dict[str, Any]) -> 'ServiceMethodDescriptor': ...

class ServiceContract:
    """Service contract definition."""
    def __init__(self, service_name: str) -> None: ...
    service_name: str
    version: str  # Version string
    description: str
    methods: List[ServiceMethodDescriptor]
    dependencies: List[str]
    capabilities: int  # ServiceCapability bitfield
    metadata: Dict[str, Any]
    def add_method(self, method: ServiceMethodDescriptor) -> None: ...
    def has_method(self, method_name: str) -> bool: ...
    def get_method(self, method_name: str) -> Optional[ServiceMethodDescriptor]: ...
    def is_compatible_with(self, other: 'ServiceContract') -> bool: ...
    def to_json(self) -> Dict[str, Any]: ...
    @staticmethod
    def from_json(json_obj: Dict[str, Any]) -> 'ServiceContract': ...

# Factory Functions
def create_service_contract(service_name: str) -> ServiceContract:
    """Create a new service contract."""
    ...

def get_available_features() -> List[str]:
    """Get list of available communication features."""
    ...


